language: go
go:
  - 1.9.x
sudo: required
services:
  - docker

env:
  global:
    - CGO_ENABLED=0

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker info
  - docker version
  - sudo pip install docker-compose
  - docker-compose version

before_script:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - make
  - make docker-tag
  - make docker-push

after_success:
  - make inspect
