---
apiVersion: v1
kind: Service
metadata:
  name: go-websocket-echo-server
  labels:
    app: go-websocket-echo-server
spec:
  selector:
    app: go-websocket-echo-server
  ports:
  - port: 80
    targetPort: 8080
---
#### Ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: go-websocket-echo-server
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "80"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "80"
spec:
  rules:
  - host: ${DOMAINNAME}
    http:
      paths:
      - backend:
          serviceName: go-websocket-echo-server
          servicePort: 80
        path: /
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-websocket-echo-server
  labels:
    app: go-websocket-echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-websocket-echo-server
  template:
    metadata:
      labels:
        app: go-websocket-echo-server
    spec:
      containers:
        - name: go-websocket-echo-server
          image: skandyla/go-websocket-echo-server
          imagePullPolicy: "Always"
          ports:
            - name: http
              containerPort: 8080
